### ISSUE TITLE
问下碰到 “Couldn't find "libutility.so” 这个问题 有什么好的解决办法没？

### ISSUE THREAD

**Issue by ggchxx** [maimingliang/WxRecoderVideo#1]
问下碰到 “Couldn't find "libutility.so” 这个问题 有什么好的解决办法没？

**Comment by maimingliang** [comment]
出现这个问题，在jnilib文件夹下没有找到与你设备的CPU架构相对应的.so 文件。
我觉得最靠谱的就是 编译出对应CPU架构的.so文件。

**Comment by maimingliang** [comment]
出现这个问题，在jnilib文件夹下没有找到与你设备的CPU架构相对应的.so 文件。
我觉得最靠谱的就是 编译出对应CPU架构的.so文件。

**Comment by ggchxx** [comment]
同样的手机运行你的项目没这个问题，集成到我自己的项目时 出现这个错误。。没发现vcarmera可以自己编译的so库

**Comment by maimingliang** [comment]
你的项目是不是有其他的.so库。 是的，VCarmera只提供了armv7的.so库，而且现在都不维护了。

**Comment by maimingliang** [comment]
你的项目是不是有其他的.so库？

**Comment by thedreamwork** [comment]
@ggchxx 你的项目so库的引用不对，我可以给你发秒拍的so，可以使用所有滤镜和特效

**Comment by djgonglun** [comment]
我也是这个问题，我原封不动导入你的两个moudle,就出现了unsatisfiedlinkerror错误

**Comment by maimingliang** [comment]
试试把 你的 targetSDK 该为 22

**Comment by juhuacha18** [comment]
是你自己配制的问题 
解决方案 [http://stackoverflow.com/questions/27186726/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader](stackoverflow)

**Comment by juhuacha18** [comment]
应该是自己的配置问题 
我也遇到了一样的问题stackoverflow上有关于这个的讨论：
[传送门](http://stackoverflow.com/questions/27186726/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader)

**Comment by liuchga** [comment]
安全邮件

















  
    
      欢迎使用安全邮局系统！

**Comment by sunxu3074** [comment]
@juhuacha18 @djgonglun @ggchxx 解决了吗？我也遇到了这个问题。

**Comment by sunxu3074** [comment]
# 解决了~

1.在自己的app module和复制进来的两个module下的build.gradle下添加 
``` 
android {
    defaultConfig {
       ndk {
         abiFilters "armeabi", "armeabi-v7a", "x86"
     }
  }
}
```

2. 工程下的gradle.properties下添加 __android.useDeprecatedNdk=true__

3. 把vitamioRecorderLibrary下的libutility.so复制到app module的对应文件夹下 （要是libs就复制到libs/armeabi-v7a下 要是jniLibs就复制到src/main/jniLibs/armeabi-v7a下即可）

**Comment by AndroidEngineerChenXiaoshuang** [comment]
还是不行，我试过了你的这三种解决方法，但是还是会抛出couldn't find "libutility.so"
